### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by OneManDevz** [seldii/Module-4-MYtinerary#1]
Hello, this is not really an issue.
I just wanted to thank you (but could not reach you). 
I was stuck several days on the update function. After reviewing your code I applied few lines to mine and it is working perfectly. You saved me several frustrating hours.

Thank you very much.

**Comment by seldii** [comment]
Hey there,
I know those frustrating hours very well so happy that you benefited from my code.
You're welcome!
